#:schema https://rlbot.org/schemas/agent.json
[settings]
name = "Gabriels RLGym Bot"
loadout_file = "loadout.toml"
root_dir = ""
run_command = "..\\venv\\Scripts\\python bot.py"
run_command_linux = "../venv/bin/python bot.py"
agent_id = "rocketleagueaiproject/rlgym_gabriel"
logo_file = ""

[details]
description = """
RLGym-trainierter ML-Bot (Experimentierstand von Gabriel)
"""
fun_fact = "Trainiert mit RLGym + RocketSim"
source_link = ""
developer = "Gabriel"
language = "Python"
tags = []